### ISSUE TITLE
Change display brightness with setscreen on/off

### ISSUE THREAD

**Issue by xAsgard** [berichan/SysBot.ACNHOrders#10]
Hey berichan! I love your work and thanks for everything and to all who contributing to this!
It’s just an idea and I’m not sure, if it’s a bug, not possible or something else. When the screen is turned off, the backlight is still on. If it is to risky to turn it off „completely“ maybe the brightness can be reduced to lowest with this feature. Thanks and greetings Asgard

**Comment by berichan** [comment]
This would require an update to sys-botbase which is unlikely as the natural progression for bots will be starlink/tma2.

Once this progression happens then we can think about including more screen features :)
