### ISSUE TITLE
I am try to setup discord bot

### ISSUE THREAD

**Issue by signo94** [berichan/SysBot.ACNHOrders#13]
Dear Berichan, thanks for providing helpful guide.

I am trying to setup discord bot to my ACNH with latest Atmosphere 1.2.2.
before this, I am stuck at getting ACNH online play. I keep getting error 2155-8007.

FYI, sys-botbase installed, Mobilespawner_win is working.

**Comment by berichan** [comment]
Are you using 90DNS or dns_mitm? This looks like a DNS issue

**Comment by signo94** [comment]
90dns.
But it should be work online play ?

**Comment by Muchacho13Scripts** [comment]
90DNS blocks all connections to Nintendo Servers. That includes the Server for online multiplayer. You need to disable 90DNS to play online.

**Comment by signo94** [comment]
If I am not applying 90DNS, it will communication with Nintendo server and detect it's Modded Switch ?

Can I know if you are allowing others to using the bot for ACNH ordering and allow others to flying in, do you block 90dns ?

**Comment by berichan** [comment]
The bot needs to be run on a clean syscfw console that can connect to official servers. No one using the bot runs a custom blocking dns such as 90 dns, you won't be able to use the bot like this.

No one has been banned for only running the order bot, but if you are afraid of a ban then don't run the bot.
More information regarding bans is available here: https://nx.eiphax.tech/ban

**Comment by signo94** [comment]
Ok noted on this. Thanks
