### ISSUE TITLE
Blank DIY through orderbot. 

### ISSUE THREAD

**Issue by antkneess** [berichan/SysBot.ACNHOrders#14]
When people order through my discord (that’s the only bot I use), DIY are dropping as blank. Does t matter what DIY.

**Comment by berichan** [comment]
Can you provide an example command they are using?

**Comment by antkneess** [comment]
$ordercat 7D000016A2 57000016A2 57000016A2 5E000016A2 180000016A2 178000016A2 2C8000016A2 65000016A2

**Comment by berichan** [comment]
If you are still experiencing this issue please let me know
