### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by LinkACNH** [berichan/SysBot.ACNHOrders#23]
There is a bug with the list of abusers they are reported and they are the message but they can use the bot and you can try to link all the abusers list in 1.
The speak command is buggy too it marks an error message

**Comment by berichan** [comment]
> There is a bug with the list of abusers they are reported and they are the message but they can use the bot and you can try to link all the abusers list in 1.

This is incoherent, the abuser list works fine.

> The speak command is buggy too it marks an error message

Cannot be reproduced with this information alone. Works fine on my end.

Provide more information, screenshots, and reproduction steps if you have valid issues.

**Comment by LinkACNH** [comment]
here is what it gives me as an error for the abuse list :
The remote server returned an error: (404) Not Found.

on the other hand impossible .ban a person it marks well the ID in the txt but it does not prevent the person not to go on the island

+ I'm not sure if it's a good idea to use the remote server or not, but I'm sure it's a good idea to use the remote server and the remote server.
thanks in advance

Translated with www.DeepL.com/Translator (free version)

**Comment by berichan** [comment]
> The remote server returned an error: (404) Not Found.

This is usually a connection issue or incorrect permissions. Try kicking your bot and reinviting with the correct permissions.

> on the other hand impossible .ban a person it marks well the ID in the txt but it does not prevent the person not to go on the island

You need to set your `PenaltyBanCount` to something above 0 in your config.json to use the `ban` command.

> Please do not close my ticket quickly

Your original ticket read as incoherent spam, and so was closed. I do not keep tickets open on my projects that seem invalid.

**Comment by Link-kuro** [comment]
> > The remote server returned an error: (404) Not Found.
> 
> This is usually a connection issue or incorrect permissions. Try kicking your bot and reinviting with the correct permissions.
> 
> > on the other hand impossible .ban a person it marks well the ID in the txt but it does not prevent the person not to go on the island
> 
> You need to set your `PenaltyBanCount` to something above 0 in your config.json to use the `ban` command.
> 
> > Please do not close my ticket quickly
> 
> Your original ticket read as incoherent spam, and so was closed. I do not keep tickets open on my projects that seem invalid.

Hello,
Sorry to disturb but I have the same problem as this person the bot says it can not access the List of "NewAbuseList.txt" here is the error:

`[07:32:05] - 192.168.0.50: Unable to load the ban list: The remote server returned an error: (404) Not Found.`

The command ban I put the number 1 but people can still use the commands is this normal?

**Comment by Link-kuro** [comment]
> > The remote server returned an error: (404) Not Found.
> 
> This is usually a connection issue or incorrect permissions. Try kicking your bot and reinviting with the correct permissions.
> 
> > on the other hand impossible .ban a person it marks well the ID in the txt but it does not prevent the person not to go on the island
> 
> You need to set your `PenaltyBanCount` to something above 0 in your config.json to use the `ban` command.
> 
> > Please do not close my ticket quickly
> 
> Your original ticket read as incoherent spam, and so was closed. I do not keep tickets open on my projects that seem invalid.


I did what you marked but still the same mistake
