### ISSUE TITLE
Recent Ban

### ISSUE THREAD

**Issue by TAM172009** [berichan/SysBot.ACNHOrders#24]
Hello. I recently was banned from the Berichan server for having an alternate account. I recently restarted my AC island over but I did not create a new discord account. Is this why I was banned? I have not been using discord for very long and I certainly didn't mean to break any rules. Is there a way I could get unbanned? Is there something I should have done on the server after restarting that would have prevented this? I hope you can help. I really enjoyed using your server. My account username is TLZ. My old island was named Islanubar and my new island is Dorne Isle. Thank you for your help.

**Comment by berichan** [comment]
Unrelated to SysBot.ACNHOrders.
