### ISSUE TITLE
Issues with "RoleUseBot"

### ISSUE THREAD

**Issue by JuntaYuy** [berichan/SysBot.ACNHOrders#26]
I though if leaving users blank like "Users": [], allows to set the "RoleUseBot" but even when set to @everyone I denies permission to use the bot with "You are not permitted to run this command."

**Comment by moddedx** [comment]
> I though if leaving users blank like "Users": [], allows to set the "RoleUseBot" but even when set to @everyone I denies permission to use the bot with "You are not permitted to run this command."

I leave that as it is set when you first run the bot. What command are you trying to use? Some commands require sudo.

**Comment by JuntaYuy** [comment]
I was attempting to use the dodo command, but while "IgnoreAllPermissions": false, is set it will not work based off the role assigned.  even leaving as "RoleUseBot": "@everyone", I have to set ignoreall to true to get it to respond.

**Comment by moddedx** [comment]
> I was attempting to use the dodo command, but while "IgnoreAllPermissions": false, is set it will not work based off the role assigned. even leaving as "RoleUseBot": "@everyone", I have to set ignoreall to true to get it to respond.

The dodo command is a sudo command. You need to use senddodo command.
