### ISSUE TITLE
NHL file isnt being refreshed!

### ISSUE THREAD

**Issue by thelitsune** [berichan/SysBot.ACNHOrders#27]
For some reason the NHL File isnt being refreshed when people join or leave the island. Is there something i need to setup or do to make this work? it did work for a little while but now stuff picked up stays gone after.

**Comment by berichan** [comment]
Ensure `RefreshMap` is set to true in the config, otherwise provide more information about your setup and config.

**Comment by thelitsune** [comment]
Below is how config looks. Do i need to create LoadedLayerNHL.txt for it to keep a layer loaded?



{
  "AcceptingCommands": true,
  "Name": "TheLitsune",
  "Token": "",
  "Prefix": "!",
  "RoleUseBot": "@everyone",
  "Channels": [],
  "Users": [],
  "Sudo": [],
  "LoggingChannels": [],
  "IgnoreAllPermissions": false,
  "SkipConsoleBotCreation": false,
  "RequireValidInventoryMetadata": true,
  "AllowDrop": true,
  "DropConfig": {
    "AutoClean": false,
    "NoActivitySeconds": 60,
    "MaxDropCount": 7,
    "PickupCount": 5,
    "UseLegacyDrop": false,
    "WrapAllItems": false,
    "WrappingPaper": 15,
    "SkipDropCheck": false
  },
  "OrderConfig": {
    "MaxQueueCount": 50,
    "UserTimeAllowed": 500,
    "WaitForArriverTime": 60,
    "CompleteOrderMessage": "Thanks for ordering!",
    "RetryFetchDodoOnFail": true,
    "ShowIDs": false,
    "PingOnAbuseDetection": true,
    "PenaltyBanCount": 0,
    "PositionCommandCooldown": -1,
    "NHIPresetsDirectory": "presets",
    "EchoArrivingLeavingChannels": []
  },
  "DodoModeConfig": {
    "LimitedDodoRestoreOnlyMode": true,
    "DodoRestoreFilename": "Dodo.txt",
    "VisitorFilename": "Visitors.txt",
    "VisitorListFilename": "VisitorsList.txt",
    "VillagerFilename": "Villagers.txt",
    "LoadedNHLFilename": "LoadedLayerNHL.txt",
    "MinimizeDetails": false,
    "EchoDodoChannels": [],
    "EchoArrivalChannels": [],
    "EchoIslandUpdateChannels": [],
    "RefreshMap": true,
    "FreezeMap": false,
    "RefreshTerrainData": false,
    "PostDodoCodeWithNewArrivals": false,
    "SetStatusAsDodoCode": false,
    "AllowSendDodo": true,
    "ReinjectMovedOutVillagers": false,
    "DodoFontPercentageSize": 100,
    "MashB": false,
    "AutoNewDodoTimeMinutes": -1,
    "SuccessfulDodoCodeSendReaction": "",
    "CycleNHLs": false,
    "CycleNHLMinutes": 1440
  },
  "AllowClean": false,
  "AllowLookup": false,
  "AnchorFilename": "Anchors.bin",
  "ForceUpdateAnchors": false,
  "MapPlaceX": 1,
  "MapPlaceY": 81,
  "MapPullChunkSize": 4096,
  "DeleteNonCommands": false,
  "DialogueButtonPressExtraDelay": 0,
  "RestartGameWait": 0,
  "ExtraTimeConnectionWait": 1000,
  "ExtraTimeEnterAirportWait": 0,
  "AttemptMitigateDialogueWarping": false,
  "LegacyDodoCodeRetrieval": false,
  "ExperimentalFreezeDodoCodeRetrieval": false,
  "ExperimentalSleepScreenOnIdle": false,
  "AllowVillagerInjection": true,
  "HideArrivalNames": false,
  "BlockerEmoji": "\u2764",
  "FieldLayerNHLDirectory": "nhl",
  "AllowKnownAbusers": false,
  "AvoidSystemUpdate": true,
  "SignalrConfig": {
    "URIEndpoint": "",
    "AuthID": "",
    "AuthTokenOrString": ""
  },
  "Protocol": 0,
  "IP": "10.0.0.224",
  "Port": 6000,
  "UseCRLF": true
}

**Comment by berichan** [comment]
The file isn't required, it just print the currently loaded layer into it.

Are you cycling through layers or just refreshing your default map as it is on startup?

**Comment by thelitsune** [comment]
Sorry for late response! I’m just trying to run a specific layer as my file. I like to add specific items on request that don’t continue to exist after they are retrieved.

**Comment by thelitsune** [comment]
But I want the primary items on my map to remain refreshed so I figured a layer file on refresh would be a perfect template!

**Comment by berichan** [comment]
> But I want the primary items on my map to remain refreshed so I figured a layer file on refresh would be a perfect template!

If a new layer is loaded then the new layer would be refreshed, if any old items remain they will be cleared if there is no new item in that space, that's how the bot works.
