### ISSUE TITLE
game language is Chinese problem

### ISSUE THREAD

**Issue by z1006670445** [berichan/SysBot.ACNHOrders#36]
If the game language is Chinese, it seems that it is not possible to obtain the dodocode correctly
Pblic static UInt32 ChineseLanguageOffset=0x7000;
(uint)OffsetHelper. DodoAddress + (uint)OffsetHelper. ChineseLanguageOffset
Only in this way can we obtain the correct information

**Comment by z1006670445** [comment]
The same goes for TimeAddress and OnlineSessionAddress

**Comment by berichan** [comment]
There are forks that handle language-specific issues like this, sadly I no longer have the time to update the source for every language or edge-case issues.
